# 数据库配置
database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  dbname: llm_center
  charset: utf8mb4
  parseTime: true
  loc: Local

# 服务器配置
server:
  port: 8080
  mode: debug