server:
  name: "llm-center"
  host: '127.0.0.1'
  port: 3000

log:
  level: "info"
  filename: "logs/app.log"
  max_size: 100
  max_age: 7
  max_backups: 10

database:
  driver: "mysql"
  host: "120.46.188.49"
  port: 3306
  username: "root"
  password: "root"
  database: "test"
  charset: "utf8mb4"

github:
  client_id: "your_github_client_id"
  client_secret: "your_github_client_secret"
  redirect_uri: "http://localhost:3000/api/auth/github/callback"