server:
  name: "llm-center"
  host: '127.0.0.1'
  port: 4000

log:
  level: "info"
  filename: "logs/app.log"
  max_size: 100
  max_age: 7
  max_backups: 10

database:
  driver: "mysql"
  host: "120.46.188.49"
  port: 3306
  username: "llm-center"
  password: "123456"
  database: "llm-center"
  charset: "utf8mb4"
